language: node_js
node_js:
  - "11"

env:
  - EXTENSION_ID=iemlhflmgkgdhionodkeoljbkkgkmlnp

cache:
  yarn: true
  npm: true

install:
  - yarn

script:
  - echo it works!
 
delpoy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true