version: 2
jobs:
  dependencies:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  firefox:
    docker:
      - image: node:10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: testlol
          command: ls -R

  chrome:
    docker:
      - image: node:10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: testlol
          command: ls -R


# workflows:
#   version: 2
#   tagged-build:
#     jobs:
#       - dependencies:
#           filters:
#             tags:
#               only: /^v.*/
#       - firefox:
#           requires:
#             - dependencies
#           filters:
#             tags:
#               only: /^v.*/
#       - chrome:
#           requires:
#             - dependencies
#           filters:
#             tags:
#               only: /^v.*/

workflows:
  version: 2
  untagged-build:
    jobs:
      - dependencies
  tagged-build:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /^q.*/