version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:12
      - working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./
  gecko:
    docker:
      - image: circleci/node:12
      - working_directory: ~/repo
    steps:
      - attach_workspace:
        at: ./
      - run:
        name: testlol
        command: ls -R


workflows:
  version: 2
  deploy:
    jobs:
      - dependencies
      - gecko:
          requires:
            - dependencies